name: Deploy App cep aws

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write # Grant write access to packages for pushing to GHCR
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Build project
        run: mvn clean install -D skipTests
      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t ricardooshiro517/cep .
      - name: Push image docker
        run: docker push ricardooshiro517/cep

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Pull image from docker hub
      run: docker pull ricardooshiro517/cep:latest
  #  - name: Remove docker container
  #    run: docker rm -f cep-aws
    - name: Run docker container
      run: docker run -d -p 8080:8080 --name cep-aws ricardooshiro517/cep
